
#      host: localhost
#      port: 8500
#      discovery:
#        serviceName: mcf-provider



auth.service.enable: true
auth.service.white: mcf-consumer


rate.limit.enable: true
rate.limit.global.num: 1
rate.limit.global.second: 1
rate.limit.services:
  - name: mcf-provider
    num: 1
    second: 2
  - name: mcf-consumer
    num: 1
    second: 2

#spring.cloud.consul.discovery.tags: group=example-service-group,version=1.0,region=dev,userid=forezp




